import type { Metadata } from 'next';
import '@mantine/core/styles.css';
import './globals.scss';
import { CharProvider } from './context/CharCtx';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <CharProvider>
      <html lang='en'>
        <head>
          <ColorSchemeScript />
        </head>
        <body className={'bgImg'}>
          <MantineProvider>{children}</MantineProvider>
        </body>
      </html>
    </CharProvider>
  );
}
