import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import 'normalize.css';
import './globals.css';
import { CharProvider } from './context/CharCtx';
import { classes } from 'typestyle';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <CharProvider>
    <html lang='en'>
      <body className={classes(inter.className,'bgImg')}>{children}</body>
    </html></CharProvider>
  );
}
