import type { Metadata } from 'next';
import 'normalize.css';
import './globals.scss';
import { CharProvider } from './context/CharCtx';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <CharProvider>
      <html lang='en'>
        <body className={'bgImg'}>{children}</body>
      </html>
    </CharProvider>
  );
}
